"""Initial migration

Revision ID: 5f85beaa77fb
Revises: 
Create Date: 2024-06-15 01:24:16.001981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f85beaa77fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=256), nullable=False),
    sa.Column('md5_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cover'))
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('year_of_creation', sa.DateTime(), nullable=False),
    sa.Column('publish_company', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('page_amount', sa.Integer(), nullable=False),
    sa.Column('rating_sum', sa.Integer(), nullable=False),
    sa.Column('amount_of_rates', sa.Integer(), nullable=False),
    sa.Column('id_cover', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cover'], ['cover.id'], name=op.f('fk_books_id_cover_cover'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=True),
    sa.Column('id_roles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_roles'], ['roles.id'], name=op.f('fk_users_id_roles_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], name=op.f('fk_feedback_id_book_books')),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name=op.f('fk_feedback_id_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_table('genresofbooks',
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], name=op.f('fk_genresofbooks_id_book_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_genre'], ['genres.id'], name=op.f('fk_genresofbooks_id_genre_genres'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_book', 'id_genre', name=op.f('pk_genresofbooks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genresofbooks')
    op.drop_table('feedback')
    op.drop_table('users')
    op.drop_table('books')
    op.drop_table('roles')
    op.drop_table('genres')
    op.drop_table('cover')
    # ### end Alembic commands ###
